version: '3.8'

services:
  # 统一的前后端服务
  claude-duck:
    image: ghcr.io/cloxl/claude-duck-backend:latest
    container_name: claude-duck
    restart: unless-stopped
    network_mode: host  # 使用host模式访问宿主机MySQL和对外提供服务
    environment:
      - TZ=Asia/Shanghai
      - PORT=9998
    volumes:
      - ./.env:/app/.env  # 挂载环境变量文件
      - ./logs:/app/logs  # 日志目录
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9998/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
