version: '3.8'

services:
  backend:
    image: ghcr.io/cloxl/claude-duck-backend:latest
    container_name: claude-duck-backend
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
      - PORT=9998
    volumes:
      - ./.env:/app/.env
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9998/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: ghcr.io/cloxl/claude-duck-frontend:latest
    container_name: claude-duck-frontend
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
      - API_URL=http://localhost:9998
      - APP_NAME=Duck Code
      - INSTALL_COMMAND=npm install -g http://111.180.197.234:7778/install --registry=https://registry.npmmirror.com"=
      - DOCS_URL=https://swjqc4r0111.feishu.cn/docx/CJT6dbdUBofDlrxfwpNcp1klnCg
      - CLAUDE_URL=https://api.duckcode.top/api/claude
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
